version: "2"

linters:
  default: none

  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - copyloopvar
    - cyclop
    - depguard
    - dupl
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - exptostd
    - fatcontext
    - forbidigo
    - funcorder
    - funlen
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gomoddirectives
    - goprintffuncname
    - gosec
    - govet
    - iface
    - inamedparam
    - ineffassign
    - intrange
    - loggercheck
    - makezero
    - mirror
    - mnd
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnesserr
    - nilnil
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - perfsprint
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - testableexamples
    - testifylint
    - testpackage
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace

  settings:
    depguard:
      rules:
        main:
          list-mode: lax
          files:
           - "!$test"
          allow:
            - $gostd
            - github.com/mazxcv/fuzzy-funicular
        test:
          files:
           - "$test"
          allow:
            - github.com/stretchr/testify
            - $gostd
            - github.com/mazxcv/fuzzy-funicular
    errcheck:
      check-type-assertions: true
    exhaustive:
      check:
        - switch
        - map
    funcorder:
      struct-method: false
    funlen:
      lines: 100
      statements: 50
    gochecksumtype:
      default-signifies-exhaustive: false
    gocognit:
      min-complexity: 20
    gocritic:
      settings:
        captLocal:
          paramsOnly: false
        underef:
          skipRecvDeref: false
    govet:
      enable-all: true
      disable:
        - fieldalignment
      settings:
        shadow:
          strict: true
    mnd:
      ignored-functions:
        - args.Error
        - flag.Arg
        - flag.Duration.*
        - flag.Float.*
        - flag.Int.*
        - flag.Uint.*
        - os.Chmod
        - os.Mkdir.*
        - os.OpenFile
        - os.WriteFile
        - prometheus.ExponentialBuckets.*
        - prometheus.LinearBuckets
    nakedret:
      max-func-lines: 0
    nolintlint:
      allow-no-explanation: [ funlen, gocognit, golines ]
      require-explanation: true
      require-specific: true
    perfsprint:
      strconcat: false
    reassign:
      patterns:
        - ".*"
    rowserrcheck:
      packages:
        - github.com/jmoiron/sqlx
    sloglint:
      no-global: all
      context: scope
    staticcheck:
      checks:
        - all
        - -ST1000
        - -ST1016
        - -QF1008
    usetesting:
      os-temp-dir: true
    inamedparam:
      skip-single-param: true

formatters:
  enable:
    - gofmt
    - goimports
    - golines

  settings:
    golines:
      max-len: 120
    goimports:
      local-prefixes:
        - github.com/mazxcv/fuzzy-funicular
    gofmt:
      simplify: true
      rewrite-rules:
        - pattern: interface{}
          replacement: any
